---
apiVersion: v1
kind: Pod
metadata:
  name: runasreadonly
  namespace: default
spec:
  securityContext:
    runAsUser: 1001
    runAsGroup: 3001
    fsGroup: 2001
 #   supplementalGroups: [ 5000]
  containers:
    - name: runasreadonly
      image: busybox:latest
      command: ["sh", "-c", "sleep 1h"]
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true 
      volumeMounts:
        - name: sec-ctx-vol1 
          mountPath: /data 
  volumes:
    - name: sec-ctx-vol1
      emptyDir: {}