---
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo1
  namespace: default
spec:
  securityContext:
    runAsUser: 1001
    runAsGroup: 3001
    fsGroup: 2001
    supplementalGroups: [ 5000]
  containers:
    - name: sec-ctx-demo1
      image: ubuntu:latest
      command: ["sh", "-c", "sleep 1h"]
      securityContext:
        allowPrivilegeEscalation: false
       # readOnlyRootFilesystem: true
       # runAsGroup: 2000
       # runAsNonRoot: true
      #  runAsUser: 1000

      