---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-dynamic-pvc
  labels:
    app: dynamic
    type: nfs
    provion: csi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-dynamic-sc  
  volumeMode: Filesystem
