---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-config-pvc
  labels:
    app: nginx-config
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-dynamic-sc
  volumeMode: Filesystem