---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels: 
    app: nginx-server
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: nginx-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata: 
      labels:
        app: nginx-server
    spec:
      containers: 
        - name: nginx-contaner
          image: nginx:1.19.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80 
              protocol: TCP
          resources:
            limits: 
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi 
          volumeMounts:
            - name: nginx-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: one-tree-pvc 
      restartPolicy: Always
  