---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: one-tree-pv
  labels:
    app: one-tree
    type: nfs
    provion: csi
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: one-tree-pv
    volumeAttributes:
      server: 192.168.119.139
      share: /data 