---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: one-tree-pvc
  labels:
    app: one-tree
    type: nfs
    provion: csi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""  
  volumeName: one-tree-pv
  