---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster-ip
  namespace: default
  labels: 
    type: nginx-service
spec:
  type: ClusterIP
  selector: 
    app: nginx-app
  ports:
    - name: nignx-cluster-port
      protocol: TCP
      port: 8080
      targetPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
    env: test
  namespace: default
spec:
  minReadySeconds: 15
  replicas: 3
  revisionHistoryLimit: 10
  selector: 
    matchLabels:                                ## equality based operators  like == and !=,  other one set based operators like in, notin 
      app: nginx-app
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata:
      labels:
        app: nginx-app
        env: test
        tier: FrountEnd
    spec:
      
      containers:
       - name: nginx
         image: nginx
         env: 
           - name: POD_IP
             valueFrom:
               fieldRef:
                 fieldPath: status.podIP
         command: ["/bin/sh", "-c"]
         args:
           - |
             echo "<html><body><h1>Pod IP: $POD_IP</h1></body></html>" > /usr/share/nginx/html/index.html && \
             nginx -g 'daemon off;'
                   
         imagePullPolicy: IfNotPresent
         ports:
           - containerPort: 80
             protocol: TCP
         resources: 
           limits:
             cpu: 300m
             memory: 400Mi

      