---
apiVersion: v1
kind: Pod 
metadata:
  name: example-pod
spec:
  containers:
  - name: example-container
    image: alpine:latest
    command: [ "sh", "-c", "sleep 3600" ]
###    command: [ "sh", "-c", "echo 'Player initial lives: $PLAYER_INITIAL_LIVES'; echo 'UI properties file: $UI_PROPERTIES_FILE_NAME'; cat /config/game.properties; cat /config/user-interface.properties" ]
    env:
      - name: PLAYER_INITIAL_LIVES
        valueFrom:
          configMapKeyRef:
            name: example-configmap
            key:  player_initial_lives
      - name: UI_PROPERTIES_FILE_NAME
        valueFrom:
          configMapKeyRef:
            name: example-configmap
            key: ui_properties_file_name
    volumeMounts:
      - name: config-volume
        mountPath: /config
        readOnly: true
  volumes:
    - name: config-volume
      configMap:
        name: example-configmap
        items:
          - key: game.properties
            path: game.properties
          - key: user-interface.properties
            path: user-interface.properties

  

 
