---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-dynamic-sc
  labels:
    app: dynamic
    type: nfs
    provision: csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.119.139
  share: /data 
reclaimPolicy: Delete
mountOptions:
  - hard
  - rsize=1048576
  - wsize=1048576
  - timeo=600
volumeBindingMode: WaitForFirstConsumer
