---
apiVersion: v1
kind: Pod 
metadata: 
  name: hostpath-test
  labels:
    app: nginx
    env: test
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts: 
        - name: hostpath-volume
          mountPath: /data/
          readOnly: true
  volumes:
    - name: hostpath-volume
      hostPath:
        path: /mnt/disks/ssd1
        type: Directory
