---
apiVersion: v1
kind: Pod
metadata:
  name: httpdget-liveness
  labels:
    type: httpget-liveness
spec:
  containers:
    - name: httpdget-liveness
      image: registry.k8s.io/e2e-test-images/agnhost:2.40
      args:
        - liveness
      livenessProbe:
        httpGet:
         path: /healthz
         port: 8080
         httpHeaders: 
           - name: Custom-Header
             value: Awesome
        terminationGracePeriodSeconds: 5
        successThreshold: 1
        periodSeconds: 5
        initialDelaySeconds: 5
      resources:
        limits: 
          cpu: 100m
          memory: 100Mi

