---
apiVersion: v1
kind: Pod
metadata:
  name: livenessprobe-exec
  labels:
   type: liveiness-exec
   app: test
spec:
  containers:
    - name: test-liveness-exec
      image: busybox  
      args:
        - sh
        - -c
        - touch /tmp/healthy; sleep 30; rm /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          command:
            - cat 
            - /tmp/healthy
        initialDelaySeconds: 10
        periodSeconds: 5     
#   - name: test-liveness-exec1
#     image: busybox1  
#     args:
#       - sh
#       - -c
#       - touch /tmp/healthy1; sleep 30; rm /tmp/healthy; sleep 600
#     livenessProbe:
#       exec:
#         command:
#           - cat 
#           - /tmp/healthy1
#       initialDelaySeconds: 10
#       periodSeconds: 5 