---
apiVersion: v1
kind: Pod
metadata:
  name: jenkin-pod1
spec:
  resources:
    requests: 
      cpu: "150m"
      memory: "200Mi"
    limits: 
      cpu: "400m"
      memory:  "800Mi"
  containers:
    - name: jenkins-server
      image: jenkins/jenkins:lts-jdk17
