 ---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - name: mysql-test
      image: mysql:8.0
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: Admin@123
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_USER
          value: raj1
        - name: MYSQL_PASSWORD
          value: Raj@123
        