---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-app-rc
  namespace: default
  labels:
    Env: demo
    type: FrontEnd
spec:
  replicas: 3
  selector:   
    app: nginx
  template:
    metadata:
      labels: 
        app: nginx
    spec:
      containers:
         - name: nginx-web1
           image: nginx
           imagePullPolicy: IfNotPresent
           ports:
             - containerPort: 22
               protocol: TCP
           resources:
             limits: 
               cpu: 1000m
               memory: 1000Mi
             requests: 
                cpu: 500m
                memory: 500Mi   